from enum import Enum
from .dev import Dev

class Awakening(Enum):
    UNKNOWN = -1
    NONE = 0
    ENHANCED_HP = 1
    ENHANCED_ATTACK = 2
    ENHANCED_RECOVERY = 3
    REDUCE_FIRE_DAMAGE = 4
    REDUCE_WATER_DAMAGE = 5
    REDUCE_WOOD_DAMAGE = 6
    REDUCE_LIGHT_DAMAGE = 7
    REDUCE_DARK_DAMAGE = 8
    AUTO_RECOVER = 9
    RESISTANCE_BIND = 10
    RESISTANCE_DARK = 11
    RESISTANCE_JAMMER = 12
    RESISTANCE_POISON = 13
    ENHANCED_FIRE_ORBS = 14
    ENHANCED_WATER_ORBS = 15
    ENHANCED_WOOD_ORBS = 16
    ENHANCED_LIGHT_ORBS = 17
    ENHANCED_DARK_ORBS = 18
    EXTEND_TIME = 19
    RECOVER_BIND = 20
    SKILL_BOOST = 21
    ENHANCED_FIRE_ATT = 22
    ENHANCED_WATER_ATT = 23
    ENHANCED_WOOD_ATT = 24
    ENHANCED_LIGHT_ATT = 25
    ENHANCED_DARK_ATT = 26
    TWO_PRONGED_ATTACK = 27
    RESISTANCE_SKILL_BIND = 28
    ENHANCED_HEAL_ORBS = 29
    MULTI_BOOST = 30
    DRAGON_KILLER = 31
    GOD_KILLER = 32
    DEVIL_KILLER = 33
    MACHINE_KILLER = 34
    BALANCED_KILLER = 35
    ATTACKER_KILLER = 36
    PHYSICAL_KILLER = 37
    HEALER_KILLER = 38
    AWAKEN_KILLER = 39
    ENHANCE_KILLER = 40
    REDEEMABLE_KILLER = 41
    EVO_KILLER = 42
    ENHANCED_COMBOS = 43
    GUARD_BREAK = 44
    BONUS_ATTACK = 45
    ENHANCED_TEAM_HP = 46
    ENHANCED_TEAM_RECOVERY = 47
    VOID_DAMAGE_PIERCER = 48
    AWOKEN_ASSIST = 49
    SUPER_BONUS_ATTACK = 50
    SKILL_CHARGE = 51
    RESISTANCE_BIND_PLUS = 52
    EXTENDED_MOVE_TIME_PLUS = 53
    RESISTANCE_CLOUDS = 54
    RESISTANCE_IMMOBILITY = 55
    SKILL_BOOST_PLUS = 56
    HP_80_OR_MORE_ENHANCED = 57
    HP_50_OR_LESS_ENHANCED = 58
    L_DAMAGE_REDUCTION = 59
    L_INCREASED_ATTACK = 60
    SUPER_ENHANCED_COMBOS = 61
    COMBO_ORBS = 62
    SKILL_VOICE = 63
    DUNGEON_BONUS = 64
    REDUCED_HP = 65
    REDUCED_ATTACK = 66
    REDUCED_RECOVERY = 67

    @classmethod
    def _missing_(cls, value):
        Dev.log(f'Unknown awakening: {value}')
        return Awakening.UNKNOWN