from enum import Enum
from .dev import Dev

class Collab(Enum):
    UNKNOWN = -1
    NONE = 0
    RAGNAROK_ONLINE = 1
    TAIKO_NO_TATSUJIN = 2
    EMIL_CHRONICLE_ONLINE = 3
    GUNMA_NO_YABOU = 5
    CRYSTAL_DEFENDER = 6
    FAMITSU = 7
    PRINCESS_PUNT_SWEET = 8
    ANDROID = 9
    SHINRABANSHO_CHOCO = 10
    CAPYBARA_SAN = 11
    FREAK_TOWER = 12
    SENGOKU_TENKA_TRIGGER = 13
    EVANGELION = 14
    SEVEN_ELEVEN = 15
    CLASH_OF_CLANS = 16
    GROOVE_COASTER = 17
    RAGNAROK_ODYSSEY_ACE = 18
    DRAGONS_DOGMA_QUEST = 19
    TAKAOKA_CITY = 20
    MONSTER_HUNTER_4G = 21
    BATMAN = 22
    THIRTY_ONE_ICECREAM = 23
    ANGRY_BIRDS = 24
    PUZZLE_AND_DRAGONS_Z = 25
    HUNTER_X_HUNTER = 26
    HELLO_KITTY = 27
    PAD_BATTLE_TOURNAMENT = 28
    BEAMS = 29
    DRAGON_BALL = 30
    SAINT_SEIYA = 31
    ROAD_TO_DRAGON = 32
    DIVINE_GATE = 33
    SUMMONS_BOARD = 34
    PICOTTO_KINGDOM = 35
    BIKKURIMAN = 36
    ANGRY_BIRDS_EPIC = 37
    DC_UNIVERSE = 38
    CHIBI_1 = 39 # first round chibis - three kingdoms series
    FIST_OF_THE_NORTH_STAR = 40
    CHIBI_2 = 41 # second round chibis
    CHIBI_3 = 44 # third round chibis
    FINAL_FANTASY = 45
    GHOST_IN_THE_SHELL = 46
    DUEL_MASTERS = 47
    ATTACK_ON_TITAN = 48
    NINJA_HATTORI_KUN = 49
    SHONEN_SUNDAY = 50
    CROWS_X_WORST = 51 # TODO VERIFY NO OVERLAP WITH VOLTRON
    BLEACH = 52
    ACE_ATTORNEY = 55
    RUROUNI_KENSHIN = 56
    PEPPER = 57
    KINNIKUMAN = 58
    HIRUNE_HIME = 59
    MAGAZINE = 60
    MONSTER_HUNTER = 61
    KAIBUTSU_KUN = 62
    VOLTRON = 63 # TODO VERIFY NO OVERLAP WITH CROW X WORST
    FULLMETAL_ALCHEMIST = 65
    KING_OF_FIGHTERS = 66
    YU_YU_HAKUSHO = 67
    PERSONA = 68
    COCA_COLA = 69
    MAGIC_THE_GATHERING = 70
    CHRONO_MAGIA = 71
    SEVENTH_REBIRTH = 72
    CALCIO_FANTASISTA = 73
    POWER_PROS = 74
    GINTAMA = 75
    SWORD_ART_ONLINE = 76
    KAMEN_RIDER = 77
    YOKAI_WATCH_W = 78
    FATE_STAY_NIGHT = 79
    STREET_FIGHTER_V = 80
    ERROR_999 = 999
    DRAGONBOUNDS_AND_DRAGON_CALLERS = 10001

    @classmethod
    def _missing_(cls, value):
        Dev.log(f'Unknown collab: {value}')
        return Collab.UNKNOWN