from enum import Enum

class OrbSkin(Enum):
    NORMAL_ORBS = 0
    FANCY_ORBS = 1
    VALKYRIE_ORBS = 2
    ZEUS_ORBS = 3
    ATHENA_ORBS = 4
    SHINRABANSHO_CHOCO_ORBS = 5
    GRECO_ROMAN_GODS_ORBS = 6
    SFV_AE_ORBS = 7
    MYSTIC_KNIGHT_ORBS = 8
    HEALER_GIRLS_ORBS = 9
    HERA_ORBS = 10
    YU_YU_HAKUSHO_ORBS = 11
    MONSTER_HUNTER_ORBS = 12
    JAPANESE_GODS_ORBS = 13
    UNKNOWN_ORBS_14 = 14
    UNKNOWN_ORBS_15 = 15
    UNKNOWN_ORBS_16 = 16
    UNKNOWN_ORBS_17 = 17
    UNKNOWN_ORBS_18 = 18
    UNKNOWN_ORBS_19 = 19